### ISSUE TITLE
A few questions / requests

### ISSUE THREAD

**Issue by rayshan** [fj/spicy-jekyll#1]
Hi, thanks for your work on this. It works pretty well. A few questions:
- Can we make it a Gem so we can use bundler / `_config.yml` to manage it?
- Why does it expect `refname`? Can't it just iterate through everything in the `_collection` folder? It's a little redundant to have to write `_authors/author-...`
- For `previous` / `next`, can we have an option to go back to the beginning once the end is reached, and the other way around as well?
- Disable logging

**Comment by fj** [comment]
Hi @rayshan, thanks for your issue.

> Can we make it a Gem so we can use bundler / _config.yml to manage it?

Sure.

> Why does it expect refname? Can't it just iterate through everything in the _collection folder? It's a little redundant to have to write _authors/author-...

The redundancy is so you're forced to be explicit about what you want in a collection. I've seen Jekyll projects where bugs were caused by people putting item X in collection Y when it should have actually been in collection Z, for example. Here, that can't happen. I can see how one might want that to be optional, though.

> For previous / next, can we have an option to go back to the beginning once the end is reached, and the other way around as well?

That should be pretty straightforward as an option.

> Disable logging

That should also be relatively straightforward.

Can you make separate issues for each of these items so I can treat them independently?

**Comment by rayshan** [comment]
Thanks, sure thing.
